In [2]:
import numpy as np

In [2]:
q = np.matrix([[1,2,1],
               [2,2,2],
               [1,2,1]])

print(q)

[[1 2 1]
 [2 2 2]
 [1 2 1]]


In [19]:
active_set = [0,2]
inactive_set = [1]
q[np.ix_(active_set, active_set)] = 3

In [12]:

q[np.ix_(active_set, active_set)]  

matrix([[3, 3],
        [3, 3]])

In [13]:
q

matrix([[3, 2, 3],
        [2, 2, 2],
        [3, 2, 3]])

In [18]:
new_val = np.zeros(4).reshape((2, 2))

q[np.ix_(active_set, active_set)]  = new_val
q

matrix([[0, 2, 0],
        [2, 2, 2],
        [0, 2, 0]])

In [20]:
q[np.ix_(active_set, inactive_set)] 

matrix([[2],
        [2]])

In [23]:
q = np.arange(9).reshape(3,3)
q

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:

q[np.ix_(active_set, active_set)]  = 0
q 

array([[0, 1, 0],
       [3, 4, 5],
       [0, 7, 0]])

In [26]:
q[np.ix_(active_set, inactive_set)] 

array([[1],
       [7]])

In [27]:
q[np.ix_(inactive_set, active_set)] 

array([[3, 5]])

## really just some area for testing some syntax

In [8]:
q = np.arange(9).reshape((3,3))
print(Q)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
active_set_bool = [True, False, True]
inactive_set_bool = [False, True, True]

q[np.ix_(active_set_bool, inactive_set_bool)] 

array([[1, 2],
       [7, 8]])